/*     */ package settlement.entity.humanoid.ai.main;
/*     */ 
/*     */ import snake2d.util.datatypes.COORDINATEE;
/*     */ import util.data.DataO;
/*     */ import util.data.INT_O;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public class AIDataModule
/*     */ {
/*     */   private AIManager cooD;
/*     */   public final INT_O.INT_OE<AIManager> byte1;
/*     */   public final INT_O.INT_OE<AIManager> byte2;
/*     */   public final INT_O.INT_OE<AIManager> byte3;
/*     */   public final INT_O.INT_OE<AIManager> x;
/*     */   public final INT_O.INT_OE<AIManager> y;
/*     */   public final INT_O.INT_OE<AIManager> nextModule;
/*     */   public final INT_O.INT_OE<AIManager> currentModule;
/*     */   private final INT_O.INT_OE<AIManager> nextModulePrio;
/*     */   private final INT_O.INT_OE<AIManager> timesResumed;
/*     */   private final COORDINATEE coo;
/*     */   
/*     */   private AIDataModule(AIData data) {
/* 448 */     this.coo = (COORDINATEE)new COORDINATEE.Abs()
/*     */       {
/*     */         public int y()
/*     */         {
/* 452 */           return (short)AIModules.AIDataModule.this.y.get(AIModules.AIDataModule.this.cooD);
/*     */         }
/*     */ 
/*     */         
/*     */         public int x() {
/* 457 */           return (short)AIModules.AIDataModule.this.x.get(AIModules.AIDataModule.this.cooD);
/*     */         }
/*     */ 
/*     */         
/*     */         public void ySet(double dy) {
/* 462 */           AIModules.AIDataModule.this.y.set(AIModules.AIDataModule.this.cooD, (int)dy & 0xFFFF);
/*     */         }
/*     */ 
/*     */         
/*     */         public void xSet(double dx) {
/* 467 */           AIModules.AIDataModule.this.x.set(AIModules.AIDataModule.this.cooD, (int)dx & 0xFFFF); } }; data.getClass(); this.byte1 = (INT_O.INT_OE<AIManager>)new DataO.DataByte(data, "ModuleB1"); data.getClass(); this.byte2 = (INT_O.INT_OE<AIManager>)new DataO.DataByte(data, "ModuleB2"); data.getClass(); this.byte3 = (INT_O.INT_OE<AIManager>)new DataO.DataByte(data, "ModuleB3"); data.getClass(); this.x = (INT_O.INT_OE<AIManager>)new DataO.DataShort(data, "moduleX"); data.getClass(); this.y = (INT_O.INT_OE<AIManager>)new DataO.DataShort(data, "moduleY"); data.getClass(); this.nextModule = (INT_O.INT_OE<AIManager>)new DataO.DataByte(data, "ModuleNext"); data.getClass();
/*     */     this.currentModule = (INT_O.INT_OE<AIManager>)new DataO.DataByte(data, "ModuleCurrent");
/*     */     data.getClass();
/*     */     this.nextModulePrio = (INT_O.INT_OE<AIManager>)new DataO.DataByte(data, "ModulePrio");
/*     */     data.getClass();
/* 472 */     this.timesResumed = (INT_O.INT_OE<AIManager>)new DataO.DataNibble(data, "ModuleTimes"); } public COORDINATEE coo(AIManager d) { this.cooD = d;
/* 473 */     return this.coo; }
/*     */ 
/*     */ }


/* Location:              C:\Users\Administrator\Documents\Tasks\Works.Dump\SongsOfSyx\mods_development\SongsOfSyx.jar!\settlement\entity\humanoid\ai\main\AIModules$AIDataModule.class
 * Java compiler version: 16 (60.0)
 * JD-Core Version:       1.1.3
 */